views/assets/css/studyView.css
views/studyView.html

study 상세 페이지 최종 - 댓글 추가

---

views/assets/css/myPage.css
views/assets/css/myStudy.css
views/assets/js/myStudy.js
views/myPage.html
views/myStudy.html

마이페이지, 내 스터디 - 1차

---

views/assets/css/studyCreate.css
views/studyCreate.html
views/studyView.html

스터디 생성(텍스트 에디터 제외) - 완성

---

views/assets/css/myComment.css
views/assets/css/myPage.css
views/assets/css/myPost.css
views/assets/css/myProfile.css
views/assets/js/myComment.js
views/assets/js/myPost.js
views/myComment.html
views/myPage.html
views/myPost.html
views/myProfile.html
views/myStudy.html

마이페이지 포함 - 2차 수정

---

views/assets/css/inquiryView.css
views/assets/css/jobPostingCreate.css
views/assets/js/jobPostingCreate.js
views/inquiryCreate.html
views/inquiryView.html
views/jobPostingCreate.html
views/studyView.html

사소한 수정, 문의하기 - 완성

---

views/assets/css/login.css
views/login.html

로그인 수정 - Google 제거

---

views/assets/css/myComment.css
views/assets/css/myPage.css
views/assets/css/myPost.css
views/myComment.html
views/myPage.html
views/myPost.html
views/myProfile.html
views/myStudy.html

마이페이지 포함 - 4차 수정

---

views/assets/css/myComment.css
views/assets/css/myPage.css
views/assets/css/myPost.css
views/assets/css/myProfile.css
views/assets/css/myStudy.css
views/assets/js/myProfile.js
views/myComment.html
views/myPage.html
views/myPost.html
views/myProfile.html
views/myStudy.html

마이페이지 포함 - 5차 수정

---

views/header.html
views/inquiryCreate.html
views/inquiryList.html
views/inquiryView.html
views/jobPostingCreate.html
views/jobPostingView.html
views/main.html
views/studyCreate.html
views/studyView.html

헤더 부분 수정, 내가 작업한 페이지 헤더 css, js 추가

헤더 부분 수정, 내가 작업한 페이지 헤더 css, js 추가

---

views/myComment.html
views/myPage.html
views/myPost.html
views/myProfile.html
views/myStudy.html

마이페이지 헤더 - 수정

---

views/assets/css/jobPostingView.css
views/jobPostingView.html

채용공고 수정/삭제 추가

---

views/assets/css/login.css
views/assets/js/login.js
views/inquiryCreate.html
views/jobPostingCreate.html
views/login.html
views/studyCreate.html

로그인 부분 수정, 모든 파일 form 태그 추가

---

spring/moyeodream/src/main/java/com/project/moyeodream/controller/CommentController.java
spring/moyeodream/src/main/java/com/project/moyeodream/controller/PostController.java

게시글 / 댓글 1차

---

spring/moyeodream/src/main/java/com/project/moyeodream/mapper/JobpostingMapper.java
spring/moyeodream/src/main/java/com/project/moyeodream/mapper/PostMapper.java
spring/moyeodream/src/main/java/com/project/moyeodream/mapper/StudyMapper.java

매퍼 오타 수정 및 변경사항 수정

---

spring/moyeodream/src/main/java/com/project/moyeodream/domain/dao/AdminDAO.java
spring/moyeodream/src/main/java/com/project/moyeodream/domain/dao/InquiryDAO.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/AdminService.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/AdminServiceImpl.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/CommentServiceImpl.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/CommentSevice.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/InquiryService.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/InquiryServiceImpl.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/JobpostingService.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/JobpostingServiceImpl.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/MemberService.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/MemberServiceImpl.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/PostService.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/PostServiceImpl.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/StudyService.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/StudyServiceImpl.java

Service 추가 및 DAO 수정

---

spring/moyeodream/src/main/java/com/project/moyeodream/controller/AdminController.java

Admin Controller 수정

---

spring/moyeodream/src/main/resources/static/css/header.css
spring/moyeodream/src/main/resources/static/css/login.css
spring/moyeodream/src/main/resources/static/js/login.js
spring/moyeodream/src/main/resources/templates/header.html
spring/moyeodream/src/main/resources/templates/main.html

헤더 부분 로그인 추가

---

spring/moyeodream/src/main/java/com/project/moyeodream/controller/PostController.java
spring/moyeodream/src/main/resources/static/css/boardWrite.css
spring/moyeodream/src/main/resources/static/css/jobPostingCreate.css
spring/moyeodream/src/main/resources/static/css/login.css
spring/moyeodream/src/main/resources/static/css/myProfile.css
spring/moyeodream/src/main/resources/static/css/studyCreate.css
spring/moyeodream/src/main/resources/static/js/login.js
spring/moyeodream/src/main/resources/static/js/myProfile.js
spring/moyeodream/src/main/resources/templates/board/board.html
spring/moyeodream/src/main/resources/templates/board/boardWrite.html
spring/moyeodream/src/main/resources/templates/main.html
spring/moyeodream/src/main/resources/templates/myPage/myProfile.html

관심 분야 5개 제한, 간단한 수정

---

spring/moyeodream/src/main/java/com/project/moyeodream/controller/StudyController.java
spring/moyeodream/src/main/java/com/project/moyeodream/domain/dao/StudyDAO.java
spring/moyeodream/src/main/java/com/project/moyeodream/domain/vo/StudyVO.java
spring/moyeodream/src/main/java/com/project/moyeodream/mapper/StudyMapper.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/StudyService.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/StudyServiceImpl.java
spring/moyeodream/src/main/resources/mapper/StudyMapper.xml
spring/moyeodream/src/main/resources/static/js/studyCreate.js
spring/moyeodream/src/main/resources/templates/study/studyCreate.html
spring/moyeodream/src/test/java/com/project/moyeodream/controller/StudyControllerTests.java
spring/moyeodream/src/test/java/com/project/moyeodream/domain/dao/StudyDaoTests.java
spring/moyeodream/src/test/java/com/project/moyeodream/mapper/StudyMapperTests.java

Study 작성 부분 - 완성

---

spring/moyeodream/src/main/java/com/project/moyeodream/controller/AdminController.java
spring/moyeodream/src/main/java/com/project/moyeodream/domain/dao/AdminDAO.java
spring/moyeodream/src/main/java/com/project/moyeodream/domain/vo/AdminVO.java
spring/moyeodream/src/main/java/com/project/moyeodream/mapper/AdminMapper.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/AdminService.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/AdminServiceImpl.java
spring/moyeodream/src/main/resources/mapper/AdminMapper.xml
spring/moyeodream/src/test/java/com/project/moyeodream/domain/dao/AdminDaoTests.java
spring/moyeodream/src/test/java/com/project/moyeodream/mapper/AdminMapperTests.java
spring/moyeodream/src/test/java/com/project/moyeodream/service/AdminServiceTests.java

관리자 로그인 - html제외

---

spring/moyeodream/src/main/java/com/project/moyeodream/controller/StudyController.java
spring/moyeodream/src/main/java/com/project/moyeodream/domain/dao/StudyDAO.java
spring/moyeodream/src/main/java/com/project/moyeodream/domain/vo/StudyDTO.java
spring/moyeodream/src/main/java/com/project/moyeodream/mapper/StudyMapper.java
spring/moyeodream/src/main/java/com/project/moyeodream/mybatis/MyBatisConfig.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/StudyService.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/StudyServiceImpl.java
spring/moyeodream/src/main/resources/config/config.xml
spring/moyeodream/src/main/resources/mapper/StudyMapper.xml
spring/moyeodream/src/main/resources/static/css/studyView.css
spring/moyeodream/src/main/resources/templates/study/studyView.html
spring/moyeodream/src/test/java/com/project/moyeodream/controller/StudyControllerTests.java
spring/moyeodream/src/test/java/com/project/moyeodream/domain/dao/StudyDaoTests.java
spring/moyeodream/src/test/java/com/project/moyeodream/mapper/StudyMapperTests.java

스터디 조회 부분 - 임시

---

spring/moyeodream/src/test/java/com/project/moyeodream/service/StudyServiceTests.java

StudyServiceTests 추가

---

spring/moyeodream/src/main/resources/static/css/main.css

main 로그인 css 부분 수정

---

spring/moyeodream/src/main/resources/static/css/main.css
spring/moyeodream/src/main/resources/templates/main.html

main css 깨진 거 복구

---

spring/moyeodream/src/main/java/com/project/moyeodream/controller/AdminController.java
spring/moyeodream/src/main/java/com/project/moyeodream/domain/dao/AdminDAO.java
spring/moyeodream/src/main/java/com/project/moyeodream/mapper/AdminMapper.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/AdminService.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/AdminServiceImpl.java
spring/moyeodream/src/main/resources/mapper/AdminMapper.xml
spring/moyeodream/src/main/resources/static/js/adminLogin.js
spring/moyeodream/src/main/resources/templates/admin/adminLogin.html
spring/moyeodream/src/main/resources/templates/admin/adminMain.html

admin login - 추가

---

spring/moyeodream/src/main/java/com/project/moyeodream/controller/InquiryController.java
spring/moyeodream/src/main/java/com/project/moyeodream/controller/JobPostingController.java
spring/moyeodream/src/main/java/com/project/moyeodream/domain/dao/InquiryDAO.java
spring/moyeodream/src/main/java/com/project/moyeodream/domain/dao/JobpostingDAO.java
spring/moyeodream/src/main/java/com/project/moyeodream/domain/vo/InquiryDTO.java
spring/moyeodream/src/main/java/com/project/moyeodream/domain/vo/JobpostingDTO.java
spring/moyeodream/src/main/java/com/project/moyeodream/mapper/InquiryMapper.java
spring/moyeodream/src/main/java/com/project/moyeodream/mapper/JobpostingMapper.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/InquiryService.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/InquiryServiceImpl.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/JobpostingService.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/JobpostingServiceImpl.java
spring/moyeodream/src/main/resources/mapper/InquiryMapper.xml
spring/moyeodream/src/main/resources/mapper/JobpostingMapper.xml
spring/moyeodream/src/main/resources/static/css/inquiryCreate.css
spring/moyeodream/src/main/resources/static/css/inquiryList.css
spring/moyeodream/src/main/resources/static/css/inquiryView.css
spring/moyeodream/src/main/resources/static/css/jobPostingCreate.css
spring/moyeodream/src/main/resources/static/css/jobPostingView.css
spring/moyeodream/src/main/resources/static/js/inquiryCreate.js
spring/moyeodream/src/main/resources/static/js/inquiryModify.js
spring/moyeodream/src/main/resources/static/js/jobPostingCreate.js
spring/moyeodream/src/main/resources/static/js/jobPostingModify.js
spring/moyeodream/src/main/resources/templates/inquiry/inquiryCreate.html
spring/moyeodream/src/main/resources/templates/inquiry/inquiryList.html
spring/moyeodream/src/main/resources/templates/inquiry/inquiryModify.html
spring/moyeodream/src/main/resources/templates/inquiry/inquiryView.html
spring/moyeodream/src/main/resources/templates/jobPosting/jobPostingCreate.html
spring/moyeodream/src/main/resources/templates/jobPosting/jobPostingModify.html
spring/moyeodream/src/main/resources/templates/jobPosting/jobPostingView.html

채용공고, 문의하기 - 1차

---

spring/moyeodream/src/main/resources/static/css/myPage.css
spring/moyeodream/src/main/resources/static/css/myProfile.css
spring/moyeodream/src/main/resources/static/css/myStudy.css
spring/moyeodream/src/main/resources/static/js/myProfile.js
spring/moyeodream/src/main/resources/static/js/myStudy.js
spring/moyeodream/src/main/resources/templates/myPage/myPage.html
spring/moyeodream/src/main/resources/templates/myPage/myProfile.html
spring/moyeodream/src/main/resources/templates/myPage/myStudy.html

마이페이지 html, css, js - 수정

---

spring/moyeodream/src/main/resources/static/css/myPost.css
spring/moyeodream/src/main/resources/templates/myPage/myPage.html
spring/moyeodream/src/main/resources/templates/myPage/myPost.html

내 게시물 관련 html - 수정

---

spring/moyeodream/src/main/java/com/project/moyeodream/controller/MemberController.java
spring/moyeodream/src/main/java/com/project/moyeodream/domain/dao/MemberDAO.java
spring/moyeodream/src/main/java/com/project/moyeodream/mapper/MemberMapper.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/MemberService.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/MemberServiceImpl.java
spring/moyeodream/src/main/resources/mapper/MemberMapper.xml
spring/moyeodream/src/main/resources/static/css/myPost.css
spring/moyeodream/src/main/resources/templates/myPage/myPost.html

마이페이지 Member 묶음

---

spring/moyeodream/src/main/resources/static/css/myStudy.css
spring/moyeodream/src/main/resources/static/js/studyView.js
spring/moyeodream/src/main/resources/templates/study/studyView.html

myStudy.css 수정, studyView 댓글 0개 부분 수정

myStudy.css 수정, studyView 댓글 0개 부분 수정

---

spring/moyeodream/src/main/java/com/project/moyeodream/controller/MemberController.java
spring/moyeodream/src/main/java/com/project/moyeodream/domain/dao/MemberDAO.java
spring/moyeodream/src/main/java/com/project/moyeodream/mapper/MemberMapper.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/MemberService.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/MemberServiceImpl.java
spring/moyeodream/src/main/resources/mapper/MemberMapper.xml
spring/moyeodream/src/main/resources/static/css/header.css
spring/moyeodream/src/main/resources/static/css/login.css
spring/moyeodream/src/main/resources/static/js/login.js
spring/moyeodream/src/main/resources/templates/fragments/header.html

로그인 / 회원가입 - 진행중

---

spring/moyeodream/src/main/resources/static/js/myProfile.js
spring/moyeodream/src/main/resources/templates/myPage/myComment.html
spring/moyeodream/src/main/resources/templates/myPage/myPage.html
spring/moyeodream/src/main/resources/templates/myPage/myPost.html
spring/moyeodream/src/main/resources/templates/myPage/myProfile.html

마이페이지 관련 - 백엔드 2차 수정

---

spring/moyeodream/src/main/java/com/project/moyeodream/controller/MemberController.java
spring/moyeodream/src/main/resources/static/js/login.js
spring/moyeodream/src/main/resources/templates/fragments/header.html

로그인, 로그아웃 메인 url로 보내기, 회원가입 시 닉네임 받아오기 - 완성

로그인, 로그아웃 메인 url로 보내기, 회원가입 시 닉네임 받아오기 - 완성

---

spring/moyeodream/src/main/java/com/project/moyeodream/controller/FileController.java
spring/moyeodream/src/main/java/com/project/moyeodream/domain/dao/FileDAO.java
spring/moyeodream/src/main/java/com/project/moyeodream/domain/vo/FileVO.java
spring/moyeodream/src/main/java/com/project/moyeodream/mapper/FileMapper.java
spring/moyeodream/src/main/resources/config/config.xml
spring/moyeodream/src/main/resources/mapper/FileMapper.xml
spring/moyeodream/src/main/resources/static/js/login.js

File 부분 초기 세팅

---

spring/moyeodream/src/main/java/com/project/moyeodream/controller/MemberController.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/MemberServiceImpl.java
spring/moyeodream/src/main/resources/static/js/myProfile.js
spring/moyeodream/src/main/resources/templates/myPage/myComment.html
spring/moyeodream/src/main/resources/templates/myPage/myPost.html
spring/moyeodream/src/main/resources/templates/myPage/myPostDetail.html
spring/moyeodream/src/main/resources/templates/myPage/myStudy.html
spring/moyeodream/src/main/resources/templates/myPage/myStudyDetail.html

마이페이지 내 스터디, 내 게시물, 내 댓글 연결 - 수정

---

spring/moyeodream/src/main/resources/static/js/login.js
spring/moyeodream/src/main/resources/static/js/studyView.js

날짜포맷 수정, 스터디 댓글 부분 오류 수정

---

spring/moyeodream/src/main/java/com/project/moyeodream/controller/JobPostingController.java
spring/moyeodream/src/main/java/com/project/moyeodream/controller/MemberController.java
spring/moyeodream/src/main/resources/mapper/InquiryMapper.xml
spring/moyeodream/src/main/resources/templates/jobPosting/jobPostingView.html
spring/moyeodream/src/main/resources/templates/myPage/myComment.html
spring/moyeodream/src/main/resources/templates/myPage/myCommentDetail.html

마이페이지 페이지 이동 관련 - 수정

---

spring/moyeodream/src/main/java/com/project/moyeodream/controller/InquiryController.java
spring/moyeodream/src/main/resources/mapper/InquiryMapper.xml
spring/moyeodream/src/main/resources/static/css/inquiryList.css
spring/moyeodream/src/main/resources/static/css/myComment.css
spring/moyeodream/src/main/resources/static/css/myPost.css
spring/moyeodream/src/main/resources/static/css/myStudy.css
spring/moyeodream/src/main/resources/templates/myPage/myComment.html
spring/moyeodream/src/main/resources/templates/myPage/myPost.html
spring/moyeodream/src/main/resources/templates/myPage/myStudy.html

문의하기 목록 - 수정

---

spring/moyeodream/src/main/java/com/project/moyeodream/controller/MemberController.java
spring/moyeodream/src/main/resources/static/js/myPostModify.js
spring/moyeodream/src/main/resources/templates/myPage/myCommentDetail.html
spring/moyeodream/src/main/resources/templates/myPage/myPage.html
spring/moyeodream/src/main/resources/templates/myPage/myPostModify.html
spring/moyeodream/src/main/resources/templates/myPage/myStudyDetail.html
spring/moyeodream/src/main/resources/templates/myPage/myStudyModify.html

마이페이지 메뉴, 각 게시글 수정 후 페이지 이동 - 추가

---

spring/moyeodream/src/main/java/com/project/moyeodream/controller/FileController.java
spring/moyeodream/src/main/resources/static/js/jobPostingCreate.js
spring/moyeodream/src/main/resources/static/js/jobPostingModify.js
spring/moyeodream/src/main/resources/templates/jobPosting/jobPostingCreate.html
spring/moyeodream/src/main/resources/templates/jobPosting/jobPostingModify.html
spring/moyeodream/src/main/resources/templates/jobPosting/jobPostingView.html

채용 공고 이미지 파일 - 추가

---

spring/moyeodream/src/main/resources/static/css/inquiryView.css
spring/moyeodream/src/main/resources/templates/inquiry/inquiryView.html

문의 상세내용 프로필 사진 - 추가

---

spring/moyeodream/src/main/java/com/project/moyeodream/domain/dao/StudyCommentDAO.java
spring/moyeodream/src/main/java/com/project/moyeodream/domain/dao/StudyDAO.java
spring/moyeodream/src/main/java/com/project/moyeodream/domain/vo/StudyCommentDTO.java
spring/moyeodream/src/main/java/com/project/moyeodream/mapper/StudyCommentMapper.java
spring/moyeodream/src/main/java/com/project/moyeodream/mapper/StudyMapper.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/StudyCommentService.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/StudyServiceImpl.java
spring/moyeodream/src/main/resources/mapper/StudyCommentMapper.xml
spring/moyeodream/src/main/resources/mapper/StudyMapper.xml
spring/moyeodream/src/main/resources/static/js/studyView.js
spring/moyeodream/src/main/resources/templates/study/studyView.html
spring/moyeodream/src/test/java/com/project/moyeodream/domain/dao/StudyDaoTests.java
spring/moyeodream/src/test/java/com/project/moyeodream/mapper/StudyCommentMapperTests.java
spring/moyeodream/src/test/java/com/project/moyeodream/mapper/StudyMapperTests.java

스터디 프로필 임시 작업, 댓글 수정 부분 수정

---

spring/moyeodream/src/main/resources/templates/myPage/myPage.html

마이페이지 로그아웃 - 수정

---

spring/moyeodream/src/main/java/com/project/moyeodream/controller/StudyController.java
spring/moyeodream/src/main/java/com/project/moyeodream/domain/dao/StudyDAO.java
spring/moyeodream/src/main/java/com/project/moyeodream/mapper/StudyMapper.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/StudyService.java
spring/moyeodream/src/main/java/com/project/moyeodream/service/StudyServiceImpl.java
spring/moyeodream/src/main/resources/mapper/StudyMapper.xml
spring/moyeodream/src/main/resources/static/js/studyView.js
spring/moyeodream/src/main/resources/templates/study/studyView.html
spring/moyeodream/src/test/java/com/project/moyeodream/service/StudyServiceTests.java

스터디 조회수 부분 - 완성

---

spring/moyeodream/src/main/java/com/project/moyeodream/controller/JobPostingController.java
spring/moyeodream/src/main/java/com/project/moyeodream/controller/MemberController.java
spring/moyeodream/src/main/java/com/project/moyeodream/controller/StudyController.java
spring/moyeodream/src/main/resources/static/css/myPost.css
spring/moyeodream/src/main/resources/templates/fragments/header.html
spring/moyeodream/src/main/resources/templates/myPage/myComment.html
spring/moyeodream/src/main/resources/templates/myPage/myPost.html

헤더 이동 경로, 스터디 조회수, 헤더 js 수정에 따른 중복된 이름 - 수정

---

spring/moyeodream/src/main/resources/static/js/studyView.js

스터디 삭제 confirm 추가

---

spring/moyeodream/src/main/resources/static/css/login.css

login.css file 부분 수정

---

spring/moyeodream/src/main/resources/static/css/myPage.css
spring/moyeodream/src/main/resources/static/js/jobPostingModify.js
spring/moyeodream/src/main/resources/templates/jobPosting/jobPostingModify.html
spring/moyeodream/src/main/resources/templates/myPage/myProfile.html

프로필 수정 프로필 이미지 오류 - 수정

---

spring/moyeodream/src/main/java/com/project/moyeodream/controller/FileController.java
spring/moyeodream/src/main/resources/static/css/studyCreate.css
spring/moyeodream/src/main/resources/static/js/login.js
spring/moyeodream/src/main/resources/static/js/studyCreate.js
spring/moyeodream/src/main/resources/static/js/studyView.js
spring/moyeodream/src/main/resources/templates/study/studyCreate.html
spring/moyeodream/src/main/resources/templates/study/studyView.html

헤더 프로필, 스터디 프로필 - 완성, 파일 업로드 - 초반

헤더 프로필, 스터디 프로필 - 완성, 파일 업로드 - 초반

---

spring/moyeodream/src/main/java/com/project/moyeodream/controller/FileController.java
spring/moyeodream/src/main/resources/static/css/inquiryView.css
spring/moyeodream/src/main/resources/static/css/jobPostingCreate.css
spring/moyeodream/src/main/resources/static/css/jobPostingView.css
spring/moyeodream/src/main/resources/static/js/inquiryCreate.js
spring/moyeodream/src/main/resources/static/js/jobPostingCreate.js
spring/moyeodream/src/main/resources/static/js/jobPostingModify.js
spring/moyeodream/src/main/resources/templates/inquiry/inquiryModify.html
spring/moyeodream/src/main/resources/templates/jobPosting/jobPostingModify.html

문의하기, 채용공고 - 완성

---

spring/moyeodream/src/main/resources/templates/myPage/myStudy.html

마이스터디 주석 오류 해결

---

spring/moyeodream/src/main/java/com/project/moyeodream/controller/MemberController.java
spring/moyeodream/src/main/resources/static/css/myPageError.css
spring/moyeodream/src/main/resources/templates/myPage/myPageError.html
spring/moyeodream/src/main/resources/templates/myPage/myPostDetail.html

로그인 X > 마이페이지 에러 페이지 추가

---

spring/moyeodream/src/main/java/com/project/moyeodream/controller/InquiryController.java
spring/moyeodream/src/main/java/com/project/moyeodream/controller/MemberController.java
spring/moyeodream/src/main/resources/templates/fragments/header.html
spring/moyeodream/src/main/resources/templates/inquiry/inquiryList.html
spring/moyeodream/src/main/resources/templates/study/studyCreate.html

헤더 로그인X 에러 관련 - 수정

---

spring/moyeodream/src/main/java/com/project/moyeodream/controller/MainController.java

메인 컨트롤러 스크롤 리턴값 오류 수정

---

spring/moyeodream/src/main/java/com/project/moyeodream/controller/MainController.java

메인 컨트롤러 스크롤 주석 해제

---

spring/moyeodream/src/main/resources/templates/study/studyView.html

studyView 오타 수정
